// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfowqyjKLaHy4pFvh33fdUg847a75aB5w',
    appId: '1:904753818452:web:4074137d2b2605aa6636c1',
    messagingSenderId: '904753818452',
    projectId: 'note291-ada3c',
    authDomain: 'note291-ada3c.firebaseapp.com',
    storageBucket: 'note291-ada3c.appspot.com',
    measurementId: 'G-93TJE009RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CaQ6dawQLGuv616qJRa1gDmDpwlqrGI',
    appId: '1:904753818452:android:7d093ffa11b3d9366636c1',
    messagingSenderId: '904753818452',
    projectId: 'note291-ada3c',
    storageBucket: 'note291-ada3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkU1Kqp_tZVtH5Fsbw_jL1tTYiZIhlG0',
    appId: '1:904753818452:ios:992268ed199975ff6636c1',
    messagingSenderId: '904753818452',
    projectId: 'note291-ada3c',
    storageBucket: 'note291-ada3c.appspot.com',
    androidClientId: '904753818452-vb8d3unlsl3te9ju7tv9tm7m3qi0pqkm.apps.googleusercontent.com',
    iosClientId: '904753818452-rmapdf8da3qkbfc1ols1ihclj21bep7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNote291',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmkU1Kqp_tZVtH5Fsbw_jL1tTYiZIhlG0',
    appId: '1:904753818452:ios:7d7af34db88e35b36636c1',
    messagingSenderId: '904753818452',
    projectId: 'note291-ada3c',
    storageBucket: 'note291-ada3c.appspot.com',
    androidClientId: '904753818452-vb8d3unlsl3te9ju7tv9tm7m3qi0pqkm.apps.googleusercontent.com',
    iosClientId: '904753818452-u05j6ru5ffg5kiabkluv794ngdabuosr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireNote291.RunnerTests',
  );
}
